# netlify.toml (place at project root, only ONE [build] block)
[build]
  publish   = "."                # serve the current folder (your index.html/styles/app.js)
  functions = "netlify/functions"

[dev]
  publish = "."                  # same for `netlify dev`

[functions]
  node_bundler = "esbuild"